{{- if and .Values.ingress.enabled .Values.ingress.canonicalHost (without .Values.ingress.hosts .Values.ingress.canonicalHost) }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-canonical
  labels:
    {{- include "radiopath.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: '^https?://[^/]+/(.*)'
    replacement: 'https://{{ .Values.ingress.canonicalHost }}/${1}'
    permanent: true
{{- end }}
