describe('links', () => {
  before(() => {
    cy.wipe()
    cy.useradd('alice', 'alice-password-1')
    cy.login('alice', 'alice-password-1')
    cy.addSite('Alpha', 47.3, 9.3)
    cy.addSite('Bravo', 47.4, 9.45)
  })
  beforeEach(() => cy.login('alice', 'alice-password-1'))

  it('analyses a link between two sites', () => {
    cy.visit('/links/new')
    cy.get('[name=name]').type('Alpha to Bravo')
    cy.get('[name=site_a_id]').select('Alpha')
    cy.get('[name=site_b_id]').select('Bravo')
    cy.get('[name=frequency_mhz]').clear().type('145.6')
    cy.get('[name=tx_power_dbm]').clear().type('40')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-120')
    cy.contains('button', 'Save').click()
    cy.location('pathname').should('match', /^\/links\/\d+$/)
    cy.contains('h1', 'Alpha to Bravo')
    cy.contains('Link margin, median').parent().contains(/[+-]\d+\.\d dB/)
    cy.get('.panel svg')
    cy.contains('a', 'Print report').invoke('attr', 'href').then((href) => {
      cy.request(href).its('headers.content-type').should('eq', 'application/pdf')
    })
  })

  it('refuses the same site on both ends', () => {
    cy.visit('/links/new')
    cy.get('[name=name]').type('Loop')
    cy.get('[name=site_a_id]').select('Alpha')
    cy.get('[name=site_b_id]').select('Alpha')
    cy.get('[name=frequency_mhz]').clear().type('145.6')
    cy.get('[name=tx_power_dbm]').clear().type('40')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-120')
    cy.contains('button', 'Save').click()
    cy.contains('.alert-error li', 'Site A and B must differ')
  })

  it('lists, edits and deletes', () => {
    cy.visit('/links')
    cy.contains('tr', 'Alpha to Bravo').contains('145.600 MHz')
    cy.contains('tr', 'Alpha to Bravo').contains('a', 'Edit').click()
    cy.get('[name=frequency_mhz]').clear().type('433.5')
    cy.contains('button', 'Save').click()
    cy.location('pathname').should('match', /^\/links\/\d+$/)
    cy.visit('/links')
    cy.contains('tr', 'Alpha to Bravo').contains('433.500 MHz')
    cy.contains('tr', 'Alpha to Bravo').contains('button', 'Delete').click()
    cy.contains('No links yet')
  })

  it('keeps a used site', () => {
    cy.visit('/links/new')
    cy.get('[name=name]').type('Keep')
    cy.get('[name=site_a_id]').select('Alpha')
    cy.get('[name=site_b_id]').select('Bravo')
    cy.get('[name=frequency_mhz]').clear().type('145.6')
    cy.get('[name=tx_power_dbm]').clear().type('40')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-120')
    cy.contains('button', 'Save').click()
    cy.visit('/sites')
    cy.contains('tr', 'Alpha').contains('button', 'Delete').click()
    cy.contains('.alert-error', 'Site is used by a link or coverage')
    cy.contains('.table-note', '2 sites')
  })
})
