describe('share', () => {
  before(() => {
    cy.wipe()
    cy.useradd('alice', 'alice-password-1')
    cy.login('alice', 'alice-password-1')
    cy.addSite('Alpha', 47.3, 9.3)
    cy.addSite('Bravo', 47.4, 9.45)
    cy.visit('/links/new')
    cy.get('[name=name]').type('Shared link')
    cy.get('[name=site_a_id]').select('Alpha')
    cy.get('[name=site_b_id]').select('Bravo')
    cy.get('[name=frequency_mhz]').clear().type('145.6')
    cy.get('[name=tx_power_dbm]').clear().type('40')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-120')
    cy.contains('button', 'Save').click()
    cy.location('pathname').should('match', /^\/links\/\d+$/)
  })
  beforeEach(() => cy.login('alice', 'alice-password-1'))

  it('shows a link to a visitor without a session', () => {
    cy.visit('/links')
    cy.contains('tr', 'Shared link').contains('a', 'Shared link').click()
    cy.contains('button', 'Create public link').should('not.be.visible')
    cy.contains('button', 'Share').click()
    cy.contains('button', 'Create public link').should('be.visible').click()
    cy.contains('button', 'Share').should('have.class', 'btn-shared')
    cy.get('input[readonly]').should('be.visible').invoke('val').then((url) => {
      const path = url.replace(/^https?:\/\/[^/]+/, '')
      expect(path).to.match(/^\/s\/l\/\S+$/)

      cy.clearCookie('radiopath_session')
      cy.visit(path)
      cy.contains('h1', 'Shared link')
      cy.contains('.alert-info', 'Shared read-only view')
      cy.contains('Link margin, median').parent().contains(/[+-]\d+\.\d dB/)
      cy.get('.panel svg')
      cy.get('body').should('not.contain', 'alice')
      cy.contains('a', 'Edit').should('not.exist')
      cy.contains('a', 'Back').should('not.exist')
      cy.request(`${path}/report.pdf`).its('headers.content-type').should('eq', 'application/pdf')
    })
  })

  it('revokes a link share', () => {
    cy.visit('/links')
    cy.contains('tr', 'Shared link').contains('a', 'Shared link').click()
    cy.contains('button', 'Share').click()
    cy.get('input[readonly]').invoke('val').then((url) => {
      const path = url.replace(/^https?:\/\/[^/]+/, '')
      cy.contains('button', 'Revoke').click()
      cy.contains('button', 'Create public link').should('be.visible')
      cy.contains('button', 'Share').should('not.have.class', 'btn-shared')

      cy.clearCookie('radiopath_session')
      cy.request({ url: path, failOnStatusCode: false }).its('status').should('eq', 404)
      cy.request({ url: `${path}/report.pdf`, failOnStatusCode: false }).its('status').should('eq', 404)
    })
  })

  it('shows a computed coverage to a visitor', () => {
    cy.visit('/coverages/new')
    cy.get('[name=name]').type('Shared coverage')
    cy.get('[name=frequency_mhz]').clear().type('433.5')
    cy.get('[name=tx_power_dbm]').clear().type('30')
    cy.get('[name=rx_height_m]').clear().type('2')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-110')
    cy.get('[name=range_km]').clear().type('2')
    cy.get('[name=resolution_m]').clear().type('100')
    cy.contains('button', 'Save').click()
    cy.contains('button', 'Compute').click()
    cy.get('#job-badge', { timeout: 120000 }).should('have.text', 'done')

    cy.contains('button', 'Share').click()
    cy.contains('button', 'Create public link').click()
    cy.get('input[readonly]').should('be.visible').invoke('val').then((url) => {
      const path = url.replace(/^https?:\/\/[^/]+/, '')
      expect(path).to.match(/^\/s\/c\/\S+$/)

      cy.clearCookie('radiopath_session')
      cy.visit(path)
      cy.contains('h1', 'Shared coverage')
      cy.contains('h2', 'Legend')
      cy.get('#job-badge').should('not.exist')
      cy.contains('button', 'Recompute').should('not.exist')
      cy.request(`${path}/image.png`).its('headers.content-type').should('eq', 'image/png')
      cy.request(`${path}/composite.png?with=`).its('headers.content-type').should('eq', 'image/png')
      cy.request({ url: `${path}/composite.png?with=999999`, failOnStatusCode: false }).its('status').should('eq', 404)
      cy.request(`${path}/report.pdf`).its('headers.content-type').should('eq', 'application/pdf')
    })
  })
})
