CREATE TABLE coverages (
  id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name               text NOT NULL,
  site_id            bigint NOT NULL REFERENCES sites(id) ON DELETE RESTRICT,
  frequency_mhz      double precision NOT NULL CHECK (frequency_mhz BETWEEN 20 AND 20000),
  tx_power_dbm       double precision NOT NULL,
  tx_gain_dbi        double precision NOT NULL DEFAULT 0,
  tx_line_loss_db    double precision NOT NULL DEFAULT 0 CHECK (tx_line_loss_db >= 0),
  rx_height_m        double precision NOT NULL CHECK (rx_height_m BETWEEN 0.5 AND 3000),
  rx_gain_dbi        double precision NOT NULL DEFAULT 0,
  rx_line_loss_db    double precision NOT NULL DEFAULT 0 CHECK (rx_line_loss_db >= 0),
  rx_sensitivity_dbm double precision NOT NULL,
  polarization       smallint NOT NULL DEFAULT 1 CHECK (polarization IN (0,1)),
  range_m            double precision NOT NULL CHECK (range_m > 0),
  resolution_m       double precision NOT NULL CHECK (resolution_m > 0),
  created_by         text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  result_png         bytea,
  result_north       double precision,
  result_south       double precision,
  result_east        double precision,
  result_west        double precision,
  computed_at        timestamptz,
  compute_ms         integer
);
