describe('coverage', () => {
  before(() => {
    cy.wipe()
    cy.useradd('alice', 'alice-password-1')
    cy.login('alice', 'alice-password-1')
    cy.addSite('Tower', 47.35, 9.4, 20)
  })
  beforeEach(() => cy.login('alice', 'alice-password-1'))

  it('computes a coverage in the background', () => {
    cy.visit('/coverages/new')
    cy.get('[name=name]').type('Tower 2 km')
    cy.get('[name=frequency_mhz]').clear().type('433.5')
    cy.get('[name=tx_power_dbm]').clear().type('30')
    cy.get('[name=rx_height_m]').clear().type('2')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-110')
    cy.get('[name=range_km]').clear().type('2')
    cy.get('[name=resolution_m]').clear().type('100')
    cy.contains('button', 'Save').click()
    cy.location('pathname').should('match', /^\/coverages\/\d+$/)
    cy.get('#job-badge').should('have.text', 'idle')
    cy.contains('Not computed yet')

    cy.contains('button', 'Compute').click()
    cy.get('#job-badge', { timeout: 120000 }).should('have.text', 'done')
    cy.contains('h2', 'Legend')
    cy.contains('button', 'Recompute')
    cy.location('pathname').then((p) => {
      cy.request(`${p}/image.png`).its('headers.content-type').should('eq', 'image/png')
      cy.request(`${p}/composite.png?with=`).then((res) => {
        expect(res.headers['content-type']).to.eq('image/png')
        expect(res.headers['x-raster-bounds']).to.match(/^-?[\d.]+,-?[\d.]+,-?[\d.]+,-?[\d.]+$/)
      })
      cy.request({ url: `${p}/composite.png?with=999999`, failOnStatusCode: false }).its('status').should('eq', 404)
      cy.request(`${p}/report.pdf`).its('headers.content-type').should('eq', 'application/pdf')
    })
    cy.visit('/coverages')
    cy.contains('tr', 'Tower 2 km').contains('2.0 km')
  })

  it('remembers the map view', () => {
    cy.visit('/coverages')
    cy.contains('tr', 'Tower 2 km').contains('a', 'Tower 2 km').click()
    cy.get('#opacity').should('have.value', '60')
    cy.get('#circles').should('be.checked')
    cy.location('pathname').then((p) => {
      cy.request({ method: 'POST', url: `${p}/view`, form: true, body: { opacity: 35, overlays: '', circles: '0' } })
        .its('status').should('eq', 204)
      cy.reload()
      cy.get('#opacity').should('have.value', '35')
      cy.contains('35 %')
      cy.get('#circles').should('not.be.checked')
    })
  })

  it('merges a ticked overlay into one raster', () => {
    cy.visit('/coverages/new')
    cy.get('[name=name]').type('Tower 1 km')
    cy.get('[name=frequency_mhz]').clear().type('433.5')
    cy.get('[name=tx_power_dbm]').clear().type('30')
    cy.get('[name=rx_height_m]').clear().type('2')
    cy.get('[name=rx_sensitivity_dbm]').clear().type('-110')
    cy.get('[name=range_km]').clear().type('1')
    cy.get('[name=resolution_m]').clear().type('100')
    cy.contains('button', 'Save').click()
    cy.contains('button', 'Compute').click()
    cy.get('#job-badge', { timeout: 120000 }).should('have.text', 'done')

    cy.get('img.leaflet-image-layer[src*="/image.png?t="]').should('have.length', 1)
    cy.get('input[data-overlay]').should('have.length', 1).check()
    cy.get('img.leaflet-image-layer[src^="blob:"]', { timeout: 10000 }).should('have.length', 1)
    cy.get('img.leaflet-image-layer').should('have.length', 1)
    cy.get('input[data-overlay]').uncheck()
    cy.get('img.leaflet-image-layer[src*="/image.png?t="]').should('have.length', 1)
    cy.get('img.leaflet-image-layer').should('have.length', 1)
  })

  it('edits the legend without recomputing', () => {
    cy.visit('/coverages')
    cy.contains('a', 'Tower 2 km').click()
    cy.contains('td', '>= 30 dB')
    cy.contains('td', 'below 0 dB / no data')
    cy.contains('button', 'Edit legend').click()
    cy.get('#legend').should('be.visible')
    cy.get('#legend [name=min_1]').clear().type('40')
    cy.get('#legend [name=color_1]').invoke('val', '#ff0000').trigger('input')
    cy.get('#legend [name=min_4]').clear()
    cy.get('#legend').contains('button', 'Save').click()
    cy.contains('td', '>= 40 dB')
    cy.contains('td', '20 to 40 dB')
    cy.contains('td', 'below 10 dB / no data')
    cy.get('.swatch[style*="#ff0000"]')
    cy.get('#job-badge').should('have.text', 'done')
    cy.location('pathname').then((p) => {
      cy.request(`${p}/image.png`).its('headers.content-type').should('eq', 'image/png')
    })
    cy.contains('a', 'Duplicate').click()
    cy.get('[name=legend]').should('have.value', '40:#ff0000,20:#3cb43c,10:#e6dc28')
    cy.go('back')
    cy.contains('button', 'Edit legend').click()
    cy.get('#legend [name=min_2]').clear().type('40')
    cy.get('#legend').contains('button', 'Save').click()
    cy.get('.alert-error').should('contain', 'listed twice')
    cy.contains('td', '>= 40 dB')
    cy.contains('button', 'Edit legend').click()
    cy.get('#legend').contains('button', 'Reset to defaults').click()
    cy.contains('td', '>= 30 dB')
    cy.contains('td', 'below 0 dB / no data')
  })

  it('refuses too many pixels', () => {
    cy.visit('/coverages/new')
    cy.get('[name=name]').type('Too fine')
    cy.get('[name=range_km]').clear().type('300')
    cy.get('[name=resolution_m]').clear().type('10')
    cy.contains('button', 'Save').click()
    cy.contains('.alert-error li', 'Range / resolution exceeds 1000 pixels per radius')
  })
})
